services:
  minio1:
    image: minio/minio
    container_name: minio1
    ports:
      - "9001:9000"   # API
      - "9005:9001"   # Console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server http://minio1/data http://minio2/data http://minio3/data --console-address ":9001"
    volumes:
      - minio1_data:/data

  minio2:
    image: minio/minio
    container_name: minio2
    ports:
      - "9002:9000"
      - "9006:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server http://minio1/data http://minio2/data http://minio3/data --console-address ":9001"
    volumes:
      - minio2_data:/data

  minio3:
    image: minio/minio
    container_name: minio3
    ports:
      - "9003:9000"
      - "9007:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server http://minio1/data http://minio2/data http://minio3/data --console-address ":9001"
    volumes:
      - minio3_data:/data

  lb:
    image: nginx:latest
    container_name: minio_lb
    ports:
      - "9000:9000" # A API vai se conectar aqui
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    depends_on:
      - minio1
      - minio2
      - minio3

volumes:
  minio1_data:
  minio2_data:
  minio3_data: